server:
  address: 0.0.0.0
  port: 8080
spring:
  datasource:
    url: jdbc:postgresql://db:5432/restaurant_app_db
    username: postgres
    password: eralex
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: create
    database: postgresql
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    show-sql: true
    properties:
      hibernate:
        format_sql: false
logging:
  level:
    org:
      springframework:
        security: ERROR
        web: ERROR
